config/routes.rb
Rails.application.routes.draw do
  root to: 'cocktails#index'
  resources :cocktails do
    resources :doses, only: [:new, :create]
  end

  delete 'doses/:id', to: 'doses#destroy', as: :dose
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_many :ingredients, through: :doses
  has_many :doses, dependent: :destroy
  validates :name, uniqueness: true, presence: true
  mount_uploader :photo, PhotoUploader
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient
  validates :description, presence: true
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses
  has_many :cocktails, through: :doses
  validates :name, uniqueness: true, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController

  def index
    @cocktails = Cocktail.all
  end

  def show
    @cocktail = Cocktail.find(params[:id])
    @doses = @cocktail.doses
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    if @cocktail.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  private

  def cocktail_params
    params.require(:cocktail).permit(:name, :photo)
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  def new
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = Dose.new
  end

  def create
    @dose = Dose.new(dose_params)
    @dose.cocktail = Cocktail.find(params[:cocktail_id])
    @dose.save
    redirect_to cocktail_path(@dose.cocktail)
  end

  def destroy
    @dose = Dose.find(params[:id])
    @dose.destroy
    redirect_to cocktail_path(@dose.cocktail)
  end

  private

  def dose_params
    params.require(:dose).permit(:description, :ingredient_id)
  end

end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/views/cocktails/index.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url('https://static.independent.co.uk/s3fs-public/thumbnails/image/2018/05/22/13/gin-cocktails.jpg?w968h681');">
  <div class="container">
    <h1>My Virtual Cocktailbar</h1>
    <p>A great selection of even greater cocktails.</p>
    <%= link_to "Create a Cocktail", new_cocktail_path, class: "btn btn-success" %>
  </div>
</div>

<!-- <div class="cards">
  <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/breakfast.jpg)">
    Breakfast
  </div>

  <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/lunch.jpg)">
    Lunch
  </div>

  <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/dinner.jpg)">
    Dinner
  </div>
</div> -->

<div class="container">

  <div class="row">
    <% @cocktails.each do |cocktail| %>
    <div class="col-md-4">
    <%= link_to cocktail_path(cocktail) do %>
      <div class="cards">
        <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path cocktail.photo, height: 300, width: 400, crop: :fill %>')">
          <%= cocktail.name %>
        </div>
      </div>
    <% end %>
    </div>
    <% end %>
  </div>
</div>

app/views/cocktails/new.html.erb
<h1 class="container">Create a new Cocktail</h1>

<%= simple_form_for(@cocktail) do |f| %>
  <% if @cocktail.errors.any? %>
    <div class="errors-container">
      <ul>
        <% @cocktail.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="container">
    <%= f.input :photo %>
    <%= f.input :photo_cache, as: :hidden %>
    <%= f.input :name, label: false, placeholder: 'Name' %>
    <%= f.submit class: "btn btn-primary"%>
  </div>
<% end %>

<br>

<div class="container">
  <%= link_to "All Cocktails", cocktails_path %>
</div>

app/views/cocktails/show.html.erb
<div class="container">
  <h1><%= @cocktail.name %></h1>


  <ul>
    <% @doses.each do |dose|  %>
    <li> <b> <%= dose.ingredient.name %> </b> -- <%= dose.description %> <%= link_to "x", dose_path(dose), method: :delete %> </li>
    <% end %>
  </ul>

  <%= link_to "Add an Ingredient", new_cocktail_dose_path(@cocktail)%>
  <br>
  <%= link_to "All Cocktails", cocktails_path %>

</div

app/views/doses/new.html.erb
<h1 class="container">Add a new Dose</h1>

<div class="container">
  <%= simple_form_for([@cocktail, @dose]) do |f| %>
    <% if @dose.errors.any? %>
      <div class="errors-container">
        <ul>
          <% @dose.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <div class="container">
      <%= f.input :description, label: false, placeholder: 'Description' %>
      <%= f.input :ingredient_id, collection: Ingredient.all %>
      <%= f.submit class: "btn btn-primary"%>
    </div>
  <% end %>
</div>

<br>

<div class="container">
  <%= link_to "Back", cocktail_path(@cocktail) %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>

    <%= javascript_include_tag "application" %>
    <%= javascript_pack_tag "application" %>
  </body>
</html>